/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author nierema_sd2081
 */
public class Details extends javax.swing.JFrame {

    public String name;
    
    public String curFname;
    public String curMname;
    public String curLname;
    public String curEmail;
    public String curPass;
    public String curRepass;

    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        del = new javax.swing.JButton();
        vw = new javax.swing.JButton();
        et = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Logout");

        del.setText("Delete");

        vw.setText("View");

        et.setText("Edit");
        et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vw)
                        .addGap(99, 99, 99)
                        .addComponent(et)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del)
                    .addComponent(vw)
                    .addComponent(et))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etMouseClicked
        // TODO add your handling code here: edit
        Login log = new Login();
        
        String firstName;
        String lastName;
        String middle;
        String email;
        String confirmPass;

        JDialog.setDefaultLookAndFeelDecorated(true);
        Object[] selectionValues = {"firstname", "lastname", "middlename", "email", "password"};
        String initialSelection = "First Name";
        Object selection = JOptionPane.showInputDialog(null, "What do you want to edit?",
                "Edit", JOptionPane.QUESTION_MESSAGE, null, selectionValues, initialSelection);

        try {
            String myDriver = "com.mysql.jdbc.Driver";
            String myUrl = "jdbc:mysql://localhost/niere";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
            Statement st = conn.createStatement();
            if ("firstname".equals((String) selection)) {
                firstName = JOptionPane.showInputDialog("First Name");
                st.executeUpdate("update userlist set firstname = (" + "'" + firstName + "'" + ") where firstname = (" + "'" + name + "'" + ");");
                System.out.println(name);
                this.dispose();
                log.setVisible(true);
            } else if ("lastname".equals((String) selection)) {
                lastName = JOptionPane.showInputDialog("Last Name");
                st.executeUpdate("update userlist set lastname = (" + "'" + lastName + "'" + ") where firstname = (" + "'" + name + "'" + ");");
                this.dispose();
                log.setVisible(true);
            } else if ("middlename".equals((String) selection)) {
                middle = JOptionPane.showInputDialog("Middle Name");
                st.executeUpdate("update renzy set middlename = (" + "'" + middle + "'" + ") where firstname = (" + "'" + name + "'" + ");");
                this.dispose();
                log.setVisible(true);
            } else if ("email".equals((String) selection)) {
                email = JOptionPane.showInputDialog("E-Mail");
                st.executeUpdate("update userlist set email = (" + "'" + email + "'" + ") where firstname = (" + "'" + name + "'" + ");");
                this.dispose();
                log.setVisible(true);
            } else if ("password".equals((String) selection)) {
                String currentPass = JOptionPane.showInputDialog("Current Password");
                while (true) {
                    if (!currentPass.equals(curPass)) {
                        JOptionPane.showMessageDialog(null, "We are asking for your current password!");
                        currentPass = JOptionPane.showInputDialog("Current Password");
                    } else {
                        confirmPass = JOptionPane.showInputDialog("New Password");
                        st.executeUpdate("update userlist set newpassword = (" + "'" + confirmPass + "'" + "), repassword = (" + "'" + confirmPass + "'" + ") where firstname = (" + "'" + name + "'" + ");");
                        this.dispose();
                        log.setVisible(true);
                        break;
                    }
                }

            }
            conn.close();

        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_etMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JButton et;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton vw;
    // End of variables declaration//GEN-END:variables
}
